"""Project O.R.B.I.T. — Lyria mission-control audio cues.

Architectural role
------------------
The command center does not just show you what is happening — you can
hear it. Each fleet event class owns a short audio identity:

* ``ALERT_DETECTED``      — subtle rising tone: a new conjunction alert.
* ``MANEUVER_AUTHORIZED`` — confident, resolving chord: burn uplinked.
* ``MANEUVER_BLOCKED``    — low cautionary tone: Model Armor intervened.
* ``HUMAN_DISPATCH``      — urgent attention-grabbing signal: operator needed.
* ``EDGE_AUTONOMOUS``     — tight two-blip chirp: the onboard autopilot acted.

Production API note (Vertex AI Lyria)
-------------------------------------
In production each cue is generated by **Lyria on Vertex AI**
(``lyria-002``, Model Garden music model)::

    POST https://{endpoint}/v1/projects/{project}/locations/{location}/
         publishers/google/models/lyria-002:predict
    {"instances": [{"prompt": "<cue prompt>", "seed": 42}],
     "parameters": {"sample_count": 1}}
    -> predictions[0].bytesBase64Encoded   # 48 kHz stereo WAV

or through the google-genai SDK equivalent
(``client.models.generate_music(model="lyria-002", ...)``). The call is
gated behind ``ORBIT_ENABLE_REAL_LYRIA=1`` plus valid Vertex credentials;
anything else serves a deterministic **procedural synthesis** rendered
with Python's stdlib ``wave`` module — fully offline, instantly cached,
and honestly labelled in the response headers. Cues are generated once
per process per event type and memoised.
"""

from __future__ import annotations

import base64
import asyncio
import io
import math
import os
import struct
import wave
from typing import Any, Final

from geap_sim.observability import audit_logger

#: Production model identifier (Lyria on Vertex AI).
LYRIA_MODEL_ID: Final[str] = os.environ.get("ORBIT_LYRIA_MODEL_ID", "lyria-002")

#: Master switch for the real Vertex AI call (opt-in only).
_REAL_LYRIA_ENABLED: Final[bool] = os.environ.get("ORBIT_ENABLE_REAL_LYRIA", "").strip() == "1"

_SAMPLE_RATE: Final[int] = 22_050

# ---------------------------------------------------------------------------
# Procedural synthesis (offline mode)
# ---------------------------------------------------------------------------


def _frames(seconds: float) -> int:
    return int(_SAMPLE_RATE * seconds)


def _env_attack_decay(i: int, n: int, attack: float = 0.02, curve: float = 3.0) -> float:
    """Attack-decay envelope with an exponential tail, peak-normalised."""
    t = i / n
    attack_n = max(1, int(n * attack))
    if i < attack_n:
        return i / attack_n
    return math.exp(-curve * (t - attack))


def _sweep(start_hz: float, end_hz: float, seconds: float, vibrato: float = 0.0) -> bytes:
    n = _frames(seconds)
    out = []
    phase = 0.0
    for i in range(n):
        t = i / n
        freq = start_hz * (end_hz / start_hz) ** t
        if vibrato:
            freq *= 1.0 + vibrato * math.sin(2 * math.pi * 6.0 * i / _SAMPLE_RATE)
        phase += 2 * math.pi * freq / _SAMPLE_RATE
        amp = 0.55 * _env_attack_decay(i, n, attack=0.05, curve=2.2)
        out.append(amp * math.sin(phase))
    return _pack(out)


def _chord(freqs: list[float], seconds: float, stagger_s: float = 0.12, detune_beat: float = 0.0) -> bytes:
    n = _frames(seconds)
    out = [0.0] * n
    for k, f in enumerate(freqs):
        start = _frames(k * stagger_s)
        for i in range(start, n):
            local = i - start
            env = _env_attack_decay(local, n - start, attack=0.01, curve=4.0)
            tone = math.sin(2 * math.pi * f * local / _SAMPLE_RATE)
            if detune_beat:
                tone += 0.6 * math.sin(2 * math.pi * (f + detune_beat) * local / _SAMPLE_RATE)
            out[i] += 0.28 * env * tone
    return _pack(out)


def _staccato(hz: float, beeps: int, on_s: float = 0.09, off_s: float = 0.07) -> bytes:
    out: list[float] = []
    gap = [0.0] * _frames(off_s)
    for b in range(beeps):
        n = _frames(on_s)
        for i in range(n):
            t = i / _SAMPLE_RATE
            timbre = (
                math.sin(2 * math.pi * hz * t)
                + 0.35 * math.sin(2 * math.pi * 3 * hz * t)
                + 0.15 * math.sin(2 * math.pi * 5 * hz * t)
            )
            env = min(1.0, i / (_frames(on_s) * 0.08)) * math.exp(-6.0 * i / n)
            out.append(0.5 * env * timbre)
        if b < beeps - 1:
            out.extend(gap)
    return _pack(out)


def _chirp_pair(first_hz: float, second_hz: float, blip_s: float = 0.11) -> bytes:
    out: list[float] = []
    for hz in (first_hz, second_hz):
        n = _frames(blip_s)
        for i in range(n):
            t = i / _SAMPLE_RATE
            env = math.sin(math.pi * i / n)  # symmetric bump
            out.append(0.5 * env * math.sin(2 * math.pi * hz * t))
        out.extend([0.0] * _frames(0.05))
    return _pack(out)


def _pack(samples: list[float]) -> bytes:
    """Clip to [-1, 1] and encode little-endian signed 16-bit PCM."""
    clipped = (max(-1.0, min(1.0, s)) for s in samples)
    return struct.pack(f"<{len(samples)}h", *(int(s * 32767) for s in clipped))


def _wav_bytes(pcm: bytes) -> bytes:
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(_SAMPLE_RATE)
        handle.writeframes(pcm)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# Event catalogue: display name → Lyria prompt + offline renderer
# ---------------------------------------------------------------------------

_AUDIO_SPECS: Final[dict[str, dict[str, Any]]] = {
    "ALERT_DETECTED": {
        "prompt": "A subtle, rising alert tone for a space mission control room — soft sine sweep, tension building",
        "render": lambda: _wav_bytes(_sweep(320.0, 840.0, 0.9, vibrato=0.01)),
    },
    "MANEUVER_AUTHORIZED": {
        "prompt": "A confident, resolving major chord for a successful satellite maneuver — warm bells, triumphant but restrained",
        "render": lambda: _wav_bytes(_chord([261.63, 329.63, 392.0, 523.25], 1.7)),
    },
    "MANEUVER_BLOCKED": {
        "prompt": "A low, cautionary drone indicating a blocked maneuver — dark, slow, dissonant beating",
        "render": lambda: _wav_bytes(_chord([110.0, 130.81, 164.81], 1.5, stagger_s=0.04, detune_beat=1.5)),
    },
    "HUMAN_DISPATCH": {
        "prompt": "An urgent, attention-grabbing triple beep from a spacecraft operations console",
        "render": lambda: _wav_bytes(_staccato(980.0, 3)),
    },
    "EDGE_AUTONOMOUS": {
        "prompt": "A tight electronic two-blip chirp confirming autonomous onboard satellite action",
        "render": lambda: _wav_bytes(_chirp_pair(520.0, 660.0)),
    },
}

_CACHE: dict[str, bytes] = {}

#: Content-Type returned alongside every clip.
MEDIA_TYPE: Final[str] = "audio/wav"


def available_audio_events() -> tuple[str, ...]:
    """Sorted event types this module can score."""
    return tuple(sorted(_AUDIO_SPECS))


def get_audio_spec(event_type: str) -> dict[str, Any] | None:
    """Prompt/renderer spec for one event type, or ``None`` when unknown."""
    return _AUDIO_SPECS.get(event_type.strip().upper())


# ---------------------------------------------------------------------------
# Real Lyria call (production path, opt-in)
# ---------------------------------------------------------------------------


async def _lyria_generate(prompt: str) -> bytes:
    """Call Vertex AI Lyria (see module docstring); returns WAV bytes."""
    from google import genai  # imported lazily so offline demos never pay it

    client = genai.Client(vertex=True)

    def _call() -> bytes:
        response = client.models.generate_music(model=LYRIA_MODEL_ID, prompt=prompt)
        payload = getattr(response, "audio_content", None) or getattr(response, "audio_data", None)
        if not payload:
            raise RuntimeError("Lyria returned no audio content")
        raw = base64.b64decode(payload) if isinstance(payload, str) else bytes(payload)
        if not raw.startswith(b"RIFF"):
            raise RuntimeError("Lyria payload is not WAV-formatted")
        return raw

    return await asyncio.to_thread(_call)


# ---------------------------------------------------------------------------
# Public entry point used by GET /api/audio/{event_type}
# ---------------------------------------------------------------------------


async def get_event_audio(event_type: str) -> bytes | None:
    """Audio for one fleet event type; ``None`` when the type is unknown.

    Order of preference: memoised clip → real Lyria (when enabled) →
    procedural synthesis. Whatever wins is cached under its event type so
    repeated SSE-driven playback never re-renders or re-bills.
    """
    key = event_type.strip().upper()
    spec = get_audio_spec(key)
    if spec is None:
        return None
    if key in _CACHE:
        return _CACHE[key]

    clip: bytes | None = None
    source = "procedural_synthesis"
    if _REAL_LYRIA_ENABLED:
        try:
            clip = await _lyria_generate(str(spec["prompt"]))
            source = LYRIA_MODEL_ID
        except Exception as exc:  # noqa: BLE001 — degrade to synthesis, loudly
            audit_logger.log_event(
                trace_id="audio",
                agent_name="orbit.audio",
                event_type="AUDIO_LYRIA_CALL_FAILED",
                payload={"event_type": key, "error_type": type(exc).__name__, "error": str(exc)[:200]},
                status="DEGRADED",
            )
    if clip is None:
        clip = spec["render"]()

    _CACHE[key] = clip
    audit_logger.log_event(
        trace_id="audio",
        agent_name="orbit.audio",
        event_type="AUDIO_CLIP_GENERATED",
        payload={"event_type": key, "source": source, "bytes": len(clip)},
        status="OK",
    )
    return clip


__all__ = [
    "LYRIA_MODEL_ID",
    "MEDIA_TYPE",
    "available_audio_events",
    "get_audio_spec",
    "get_event_audio",
]
